### ISSUE TITLE
Incompatibility with Essentials

### ISSUE THREAD

**Issue by MatuxGG** [AJMix/TownOfImpostors#11] opened 2021-03-15 13:02 UTC
Hello,

First of all, your mod is awesome, good job !

I'm the creator of a little software called Mod Manager that allow people to switch between mods or combine them.
There is an issue with your mod that prevent people for being able to see all options in the game creation lobby (in the computer).
After some investigations, it looks like your mod has some incompatibilities with the library Reactor Essentials (https://github.com/DorCoMaNdO/Reactor-Essentials).

Is it possible for you to fix this incompatibility in next patches please ?

Best regards.

**Comment by AJMix** [comment] 2021-03-15 18:45
Hi MatuxGG,

Thanks for getting in touch. This mod doesn't make use of Reactor, but this compatibility issue with the Reactor Essentials library can definitely be looked into. Will look to hopefully get this issue fixed in in the next patch, if possible, so it can work with your Mod Manager - I'll put an update here when the issue is resolved 👍 

Best.

**Comment by MatuxGG** [comment] 2021-03-16 08:31
Thanks a lot

**Comment by AJMix** [comment] 2021-03-20 19:39
Town Of Impostors should now be compatible from 1.6.0 onwards.

It is still not guaranteed to work as intended if installed from the Mod Manager as not everything was tested. Closing this issue for now but do feel free to open another issue if more problems are found

**Closed by AJMix** 2021-03-20 19:39 UTC
