### ISSUE TITLE
update for among us 2021.4.1s

### ISSUE THREAD

**Issue by Pietrodjaowjao** [AJMix/TownOfImpostors#33] opened 2021-04-07 19:44 UTC
update the mod for the among us version v2021.4.2s

**Comment by JonyKasual** [comment] 2021-04-07 20:09
Duplicate of #29. Closing Issue.

I will quote what I posted there:
> I'll see what @AJMix says, but it is unlikely. Each mod version is released specifically for the stated game version due to the obfuscation unique to each game build. He would not only have to do a lot more work figuring out mappings on two versions, but moreso for a public beta version that is subject to more regular new builds that would break the work done for the build before it.

As far as I know, the latest stable release is currently **v2021.3.31.3s** as of this writing. If this is an issue regarding having trouble installing the mod because you don't see that version in your game, please check if you have opted into the Among Us public beta. This mod currently does not plan to support the public beta version.

**Closed by JonyKasual** 2021-04-07 20:09 UTC

**Comment by cocoADHD** [comment] 2021-04-11 10:49
OMG it took me hours to find this and realize I have public beta enabled! lol
