### ISSUE TITLE
I can play 

### ISSUE THREAD

**Issue by hytboy** [AJMix/TownOfImpostors#25] opened 2021-04-05 02:08 UTC
hallo I intalled the mod normaly but wenn i am in the lobby the use button im ligting the all time , I cant go on the laptop and when i am in the game i cant to the task  and the report is on the all time  , the settings  to inthe game 
![Icantplay](https://user-images.githubusercontent.com/81940511/113529674-55c47880-95c4-11eb-8327-257e218dd195.png)
![Icantgoonlaptop](https://user-images.githubusercontent.com/81940511/113529754-9623f680-95c4-11eb-93f0-9137aa7c493f.png)

**Comment by AJMix** [comment] 2021-04-05 11:35
There's an additonal **>>Made by Zirno#9723**.

Could you let me know if you loaded any other mod with this mod or if you installed via some mod manager? The mod may not be guaranteed to work as intended if you did any of those.

**Comment by hytboy** [comment] 2021-04-05 12:40
I loaded only the mod on my copy among us folder

**Comment by JonyKasual** [comment] 2021-04-05 21:03
Hi, please attach your LogOutput.log found in the modded Among Us > BepInEx folder after launching the modded game once, but as @AJMix said, we suspect that additional mods are being loaded.

Please also check that the original Among Us folder you are copying from is not already modified. If that directory contains any more than what you see below before you began installing Town Of Impostors, it has already been modded.
```
.
├── Among Us_Data
├── Among Us.exe
├── baselib.dll
├── GameAssembly.dll
├── UnityCrashHandler32.exe
└── UnityPlayer.dll
```
If your clean Among Us directory looks exactly like that with nothing else, please have Steam verify integrity of game files, then reattempt installation.

**Comment by hytboy** [comment] 2021-04-06 13:44
so this my normal among us file and logoutput : 
![image](https://user-images.githubusercontent.com/81940511/113716345-c82f7880-96ea-11eb-8946-2b00a75eba70.png)
[LogOutput.log](https://github.com/AJMix/TownOfImpostors/files/6265023/LogOutput.log)
so this is my among us town of impostors file and logoutput : 
![image](https://user-images.githubusercontent.com/81940511/113718181-afc05d80-96ec-11eb-81e6-df745cc09a9e.png)
[LogOutput.log](https://github.com/AJMix/TownOfImpostors/files/6264960/LogOutput.log)
there you see my two files and logoutput am only loading this mod and nothing else 
so please help me  go throw this problem

**Comment by hytboy** [comment] 2021-04-06 15:46
i fix it my among us file  had another  mod in it

**Comment by AJMix** [comment] 2021-04-06 18:20
Closing issue as it has been resolved.

**Closed by AJMix** 2021-04-06 18:20 UTC
