### ISSUE TITLE
cooldown bug

### ISSUE THREAD

**Issue by Andrzejone** [AJMix/TownOfImpostors#28] opened 2021-04-05 21:47 UTC
Hi.
Some abilities of roles have cooldown time bugs.
Ex. Trickster sometimes can spawn clone with no time out (time to vanish display "0" and clone is standing forever, unless killed or some other action making him dissapear)
Impostor can disguise with no time out (happening sometimes, couldn't reproduce the situation to make it, so idk conditions like with trickster) also when Impostor in disguise, and meeting is called (thru button or report)  his true identity is revealed.
Impostors some times (happened 2 times for now) can see informant and indicator for his position from the beggining of the game.
also
Will update it with more info

**Comment by JonyKasual** [comment] 2021-04-06 00:00
Thanks for reporting this.

The infinite duration clones and disguise will be fixed on the next release.

As for the Impostor in disguise and his true identity being revealed on a meeting call, could you give more info? Disguise being removed going into a meeting is intended. However, if there is a point where you can literally see a player lose their disguise on a report or during a meeting (and thus revealing they are the impostor), that is not intended.

**Comment by AJMix** [comment] 2021-04-06 00:25
Hey Andrze,

Thanks for reporting these issues. The Impostor being revealed by his disguise turning off as a meeting is called will be fixed in the next release.

We're currently looking into Informants being revealed at the beginning of the game. If you get anymore information on this please let us know.

**Comment by AJMix** [comment] 2021-04-06 21:35
Bugs mentioned here have been resolved in 1.7.1.

Only issue we couldn't reproduce was the Informant bug mentioned here. 

Closing this issue for now, but if the Informant bug pops back up again please feel free to open another issue.

**Closed by AJMix** 2021-04-06 21:35 UTC
