### ISSUE TITLE
Recommended Settings

### ISSUE THREAD

**Issue by Hadreshikrar** [AJMix/TownOfImpostors#1] opened 2021-03-09 11:15 UTC
Each time the game ends or someone joins the game the recommended settings checkbox will change and all custom settings are lost, only way to get customer settings for all players is for everyone to start at the computer on the game tab and for the host to reset the recommendation settings on and off

**Comment by AJMix** [comment] 2021-03-09 12:50
> Each time the game ends or someone joins the game the recommended settings checkbox will change and all custom settings are lost, only way to get customer settings for all players is for everyone to start at the computer on the game tab and for the host to reset the recommendation settings on and off

Hey Hadresh,

First off, please double check that you're using the right version of among us and that you've followed installation instructions properly.

I can't seem to reproduce your issue. From my testing, it seems the custom settings are working fine and all settings are synced between all players, even when a player joins or game ends.

It sounds like there's an issue with your system not being able to write to PlayerPrefs (which is what unity uses to save data, like the settings). Please double check that your settings are actually being saved, even without the mod (try vanilla among us).

I'd be happy to assist further if you can provide me with more details.

**Comment by AJMix** [comment] 2021-03-10 10:39
Hi Hadresh,

Good news, we've managed to get a repro on this issue! Looks like it's a new issue introduced after the mod was updated to be compatible with the latest among us. A fix for this is coming in 1.3.1, please keep an eye out for that 👍

**Closed** 2021-03-10 22:01 UTC
