### ISSUE TITLE
Disguise issue

### ISSUE THREAD

**Issue by Andrzejone** [AJMix/TownOfImpostors#32] opened 2021-04-07 17:20 UTC
When you being Impostor, use disguise to person who you killing and jump to vent with his body, the disguise stay forever (to end of the round) It's only occur with first kill in game.
Lovers and Impostor chat is mixed. When one lover is impostor, the other Impostor will see his messages, but second Lover won't

**Comment by JonyKasual** [comment] 2021-04-07 18:34
Thanks for reporting this.

I've managed to re-produce the disguise issue, so I'll forward that to @AJMix.

As for what I think you are trying to say for: 
The chat between an Impostor & Lover Crewmate being wrongly seen by the other Impostor
OR
The chat between an Impostor & Impostor being wrongly seen by the Lover in love with one of the Impostors.
I have not been able to reproduce these scenarios but I will mention them nonetheless. 

Please double check though that the Impostor (Lover) is on the right comms when they type their messages. It is possible to switch between Lover Comms and Impostor Comms (who they privately message to) with this button to the right of the message log:
![image](https://user-images.githubusercontent.com/81447060/113916150-8d573e80-97d7-11eb-8c02-376c2821fa23.png)
![image](https://user-images.githubusercontent.com/81447060/113916487-f048d580-97d7-11eb-8512-b4ada3feceb6.png)
![image](https://user-images.githubusercontent.com/81447060/113916515-f63eb680-97d7-11eb-8f5e-7e93df5f728e.png)

**Comment by AJMix** [comment] 2021-04-07 21:27
Thanks for reporting these issues.

JonyKasual and I have discovered the cause of the infinite disguise - please avoid toggling on the custom option "Impostors Can Kill Each Other" for now until this is fixed 🙂

**Comment by Andrzejone** [comment] 2021-04-08 12:13
> Thanks for reporting this.
> 
> I've managed to re-produce the disguise issue, so I'll forward that to @AJMix.
> 
> As for what I think you are trying to say for:
> The chat between an Impostor & Lover Crewmate being wrongly seen by the other Impostor
> OR
> The chat between an Impostor & Impostor being wrongly seen by the Lover in love with one of the Impostors.
> I have not been able to reproduce these scenarios but I will mention them nonetheless.
> 
> Please double check though that the Impostor (Lover) is on the right comms when they type their messages. It is possible to switch between Lover Comms and Impostor Comms (who they privately message to) with this button to the right of the message log:
> ![image](https://user-images.githubusercontent.com/81447060/113916150-8d573e80-97d7-11eb-8c02-376c2821fa23.png)
> ![image](https://user-images.githubusercontent.com/81447060/113916487-f048d580-97d7-11eb-8512-b4ada3feceb6.png)
> ![image](https://user-images.githubusercontent.com/81447060/113916515-f63eb680-97d7-11eb-8f5e-7e93df5f728e.png)

Gonna suggest to test this to fellows, can't run much instances of game to try it myself.

**Comment by AJMix** [comment] 2021-04-11 12:35
Issues mentioned here should be fixed in 1.8.1 release

Closing this issue

**Closed by AJMix** 2021-04-11 12:35 UTC
