### ISSUE TITLE
Can't run among us other roles or town of impostors mod

### ISSUE THREAD

**Issue by saambac** [AJMix/TownOfImpostors#10] opened 2021-03-15 08:12 UTC
I installed and pasted everything exactly as instructed but among us mods won't open. It runs in the background and eventually slows my pc. Please give me a solution for this.

**Comment by AJMix** [comment] 2021-03-15 18:48
Hi Saambac,

You'll have to raise an issue in "The Other Roles" github repo and get in contact with the developer there for that among us mod.

For Town Of Impostors, I'm going to need more details in order to provide help and potential solutions. Could I get your PC specs? How well does Among Us run without mods?

If you are struggling to run any mod for Among Us then it could likely be an issue with your system itself.

Maybe try reinstalling cpp libs (refer to troubleshooting section, third bullet point) and see how that goes.

Best.

**Comment by saambac** [comment] 2021-03-17 11:27
Thanx for replying AJMix. First of all, I can run sheriff mod. for now I can't run town of impostors mod and the other roles mod. I haven't tried any other mods. Moreover, town of impostors mod did run once or twice a while ago(probably a week) but it doesn't run now.
thank you in advance

**Comment by AJMix** [comment] 2021-03-19 14:20
Hi Saambac,

I'm not sure what the issue could be. You can attach your logs here by going into your among us folder -> BepInEx and there should be a LogOutput in there. If there is, please attach that here.

Other than that, please note a few more things:
- This mod was made for Windows/PC Steam version of the, if you're using any other OS or other version of the game, this mod will not work as intended
- Please make sure you're using the right version of Among Us (latest release on Steam) with the correct version of the mod.

Best.

**Comment by JonyKasual** [comment] 2021-03-29 21:14
Closing this for now. 

Reiterating that this mod was not intended to be used alongside other mods _unless_ compatibility has been explicitly stated.

If the issue is persisting after @AJMix's recommendations, you may open a new issue with the requested **LogOutput.log** found in your modded Among Us\BepInEx\ in addition to info about your system.

**Closed by JonyKasual** 2021-03-29 21:14 UTC
